### PR TITLE
146 markdown button fix

### LINKED ISSUE #146: Duplicatating sections - button implementer doesn't work.
image

### PR DESCRIPTION
**Pull request by rorJeremy**
- Render actual quotes in link text, rather than some jumbled up code that represents a quote
- Allow us to use multiple links in our markdown that have classes that are all the same, and will all be rendered as html as you would expect

closes #146

### CODE REVIEW

File: wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb [hunk 1]
```diff
@@ -9,6 +9,12 @@
     ' Last line goes here [Test](https://test.com).'
   }
 
+  let(:markdown_string_with_links_that_have_classes2) {
+    +"Ministry by [Awaken](/awaken \"Awaken's Homepage\"){: .button .white} in Dallas, Texas."\
```
Comment (jpowell) [inline wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb]:
```ruby
<<-WHATEVER
  Ministry by [Awaken](/awaken \"Awaken's Homepage\"){: .button .white} in Dallas, Texas.
  Ministry by [Awaken](/awaken \"Awaken's Homepage\"){: .button .white} in Dallas, Texas.
  Ministry by [Awaken](/awaken \"Awaken's Homepage\"){: .button .white} in Dallas, Texas.
WHATEVER
```

File: wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb [hunk 2]
```diff
@@ -317,11 +363,17 @@
...
+        ' [Watermark Community Church](http://www.watermark.org)'\
+        ' [Test](https://test.com).'
+
       expect(text.include?('{: .button .white}')).to be true
 
-      helper.remove_markdown_href_class_syntax(raw_classes, text)
+      transformed_text = helper.remove_markdown_href_class_syntax(raw_classes, text)
 
-      expect(text.include?('{: .button .white}')).to be false
+      expect(transformed_text.include?('{: .button .white}')).to be false
```
Comment (jpowell) [inline wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb]: `expect(transformed_text).to_not include('{: .button .white}')` works also

Comment (jpowell) [reply wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb]: https://relishapp.com/rspec/rspec-expectations/v/3-8/docs/built-in-matchers/predicate-matchers

Comment (rorJeremy) [reply wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb]: Yeah, that's much nicer.

File: wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb [hunk 3]
```diff
@@ -317,11 +363,17 @@
         ' [Watermark Community Church](http://www.watermark.org){: .button-medium .green}'\
         ' [Test](https://test.com).'
 
+      text_without_class_syntax =
+        +"Ministry developed by [Awaken](/awaken \"Awaken's Homepage\")"\
```
[the remark this answers is not in the document]
Comment (rorJeremy) [reply wcc-contentful-app/spec/helpers/wcc/contentful/app/section_helper_spec.rb]: Oops! I should've checked the rest of the spec for these. I replaced them all now.

File: wcc-contentful-app/app/helpers/wcc/contentful/app/section_helper.rb [hunk 4]
```diff
@@ -53,11 +53,12 @@ def markdown(text)
     }
 
     renderer = ::WCC::Contentful::App::CustomMarkdownRender.new(options)
-    remove_markdown_href_class_syntax(raw_classes, text)
     markdown = ::Redcarpet::Markdown.new(renderer, extensions)
 
     content_tag(:div,
-      markdown.render(text).html_safe,
+      CGI.unescapeHTML(markdown.render(
```
Comment (jpowell) [inline wcc-contentful-app/app/helpers/wcc/contentful/app/section_helper.rb]: Do you need to unescape? `html_safe` could be enough?

Comment (rorJeremy) [reply wcc-contentful-app/app/helpers/wcc/contentful/app/section_helper.rb]: Yeah, the html_safe had been there the entire time, but the unescape was the trick. Check it out:
```
text
#=> [Children's](https://watermark.formstack.com/forms/childrensvolunteer)
remove_markdown_href_class_syntax(raw_classes, text)
#=> [Children's](https://watermark.formstack.com/forms/childrensvolunteer)
markdown.render(remove_markdown_href_class_syntax(raw_classes, text))
#=> <p><a target="_blank" href="https://watermark.formstack.com/forms/childrensvolunteer">Children&amp;#39;s</a></p>
markdown.render(remove_markdown_href_class_syntax(raw_classes, text)).html_safe
#=> <p><a target="_blank" href="https://watermark.formstack.com/forms/childrensvolunteer">Children&amp;#39;s</a></p>
CGI.unescapeHTML(markdown.render(remove_markdown_href_class_syntax(raw_classes, text))).html_safe
#=> <p><a target="_blank" href="https://watermark.formstack.com/forms/childrensvolunteer">Children&#39;s</a></p>
```
